using System;

namespace fiskaltrust.MiddlewareWrapperAtrust.Test.Interop
{
    public class ATrustException : Exception
    {
        public ATrustResult Result { get; set; }

        public ATrustException() { }

        public ATrustException(string message) : base(message) { }

        public ATrustException(string message, Exception innerException) : base(message, innerException) { }

        public ATrustException(string message, ATrustResult result) : base(message)
        {
            Result = result;
        }
    }

    public static class ATrustResultExtensions
    {
        public static void ThrowIfError(this ATrustResult result)
        {
            if (result != ATrustResult.EXECUTION_OK)
            {
                throw new ATrustException($"An error occurred when calling the a.sign library: {result}", result);
            }
        }
    }

    public enum ATrustResult
    {
        ERROR_MISSING_PARAMETER = -3000,
        ERROR_FUNCTION_NOT_SUPPORTED = -3001,
        ERROR_IO = -3002,
        ERROR_TSE_TIMEOUT = -3003,
        ERROR_ALLOCATION_FAILED = -3004,
        ERROR_CONFIG_FILE_NOT_FOUND = -3005,
        ERROR_SE_COMMUNICATION_FAILED = -3006,
        ERROR_TSE_COMMAND_DATA_INVALID = -3007,
        ERROR_TSE_RESPONSE_DATA_INVALID = -3008,
        ERROR_ERS_ALREADY_MAPPED = -3009,
        ERROR_NO_ERS = -3010,
        ERROR_TSE_UNKNOWN_ERROR = -3011,
        ERROR_STREAM_WRITE = -3012,
        ERROR_BUFFER_TOO_SMALL = -3013,
        ERROR_NO_SUCH_KEY = -3014,
        ERROR_NO_KEY = -3015,
        ERROR_SE_API_DEACTIVATED = -3016,
        ERROR_SE_API_NOT_DEACTIVATED = -3017,
        ERROR_AT_LOAD_NOT_CALLED = -3018,
        ERROR_UNKNOWN = -3100,
        ERROR_AUTHENTICATION_FAILED = -4000,
        ERROR_UNBLOCK_FAILED = -4001,
        ERROR_RETRIEVE_LOG_MESSAGE_FAILED = -5001,
        ERROR_STORAGE_FAILURE = -5002,
        ERROR_UPDATE_TIME_FAILED = -5003,
        ERROR_PARAMETER_MISMATCH = -5004,
        ERROR_ID_NOT_FOUND = -5005,
        ERROR_TRANSACTION_NUMBER_NOT_FOUND = -5006,
        ERROR_NO_DATA_AVAILABLE = -5007,
        ERROR_TOO_MANY_RECORDS = -5008,
        ERROR_START_TRANSACTION_FAILED = -5009,
        ERROR_UPDATE_TRANSACTION_FAILED = -5010,
        ERROR_FINISH_TRANSACTION_FAILED = -5011,
        ERROR_RESTORE_FAILED = -5012,
        ERROR_STORING_INIT_DATA_FAILED = -5013,
        ERROR_EXPORT_CERT_FAILED = -5014,
        ERROR_NO_LOG_MESSAGE = -5015,
        ERROR_READING_LOG_MESSAGE = -5016,
        ERROR_NO_TRANSACTION = -5017,
        ERROR_SE_API_NOT_INITIALIZED = -5018,
        ERROR_TIME_NOT_SET = -5019,
        ERROR_CERTIFICATE_EXPIRED = -5020,
        ERROR_SECURE_ELEMENT_DISABLED = -5021,
        ERROR_USER_NOT_AUTHORIZED = -5022,
        ERROR_USER_NOT_AUTHENTICATED = -5023,
        ERROR_DESCRIPTION_NOT_SET_BY_MANUFACTURER = -5024,
        ERROR_DESCRIPTION_SET_BY_MANUFACTURER = -5025,
        ERROR_EXPORT_SERIAL_NUMBERS_FAILED = -5026,
        ERROR_GET_MAX_NUMBER_OF_CLIENTS_FAILED = -5027,
        ERROR_GET_CURRENT_NUMBER_OF_CLIENTS_FAILED = -5028,
        ERROR_GET_MAX_NUMBER_TRANSACTIONS_FAILED = -5029,
        ERROR_GET_CURRENT_NUMBER_OF_TRANSACTIONS_FAILED = -5030,
        ERROR_GET_SUPPORTED_UPDATE_VARIANTS_FAILED = -5031,
        ERROR_DELETE_STORED_DATA_FAILED = -5032,
        ERROR_UNEXPORTED_STORED_DATA = -5033,
        ERROR_SIGNING_SYSTEM_OPERATION_DATA_FAILED = -5034,
        ERROR_USER_ID_NOT_MANAGED = -5035,
        ERROR_USER_ID_NOT_AUTHENTICATED = -5036,
        ERROR_DISABLE_SECURE_ELEMENT_FAILED = -5037,
        ERROR_CONFIG_VALUE_NOT_FOUND = -5038,
        ERROR_INVALID_CONFIG = -5039,
        ERROR_SUSPEND_SECURE_ELEMENT_FAILED = -5040,
        ERROR_UNSUSPEND_SECURE_ELEMENT_FAILED = -5041,
        ERROR_GET_OPEN_TRANSACTIONS_FAILED = -5042,
        ERROR_GET_LIFECYCLE_STATE_FAILED = -5043,
        ERROR_GET_TRANSACTION_COUNTER_FAILED = -5044,
        ERROR_GET_SIGNATURE_ALGORITHM_FAILED = -5045,
        // ERROR_GET_SIGNATURE_COUNTER_FAILED = -5045,
        ERROR_GET_TOTAL_LOG_MEMORY = -5046,
        ERROR_GET_LOG_TIME_FORMAT = -5047,
        ERROR_EXPORT_PUBLIC_KEY_FAILED = -5048,
        ERROR_EXPORT_CERTIFICATE_FAILED = -5049,
        ERROR_TPM_CONNECT = -5050,
        ERROR_INVALID_CLIENT_ID = -5051,
        ERROR_CLIENT_ID_NOT_REGISTERED = -5052,
        ERROR_CLIENT_ID_REGISTRATION_FAILED = -5053,
        ERROR_CANNOT_RETRIEVE_REGISTERED_CLIENT_IDS = -5054,
        ERROR_CORRUPTED_REGISTERED_CLIENT_IDS = -5055,
        ERROR_CORRUPTED_APP_DATA = -5056,
        ERROR_SET_PINS_FAILED = -5057,
        ERROR_SE_ALREADY_INITIALIZED = -5058,
        ERROR_UNSUPPORTED_PREMIUM_FEATURE = -6000,
        EXECUTION_OK = 0
    }
}
